---
title: "NEO Personality Inventory-Revised (NEO PI-R)"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{NEO-PI-R}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
devtools::load_all(".")
```

# Background
_Information grabbed from [psychpress](https://www.psychpress.com.au/talent-management-solutions/identify-talent/psychometric-testing/NEO-PI-R/index.php)_
The NEO PI-R provides a comprehensive and detailed assessment of adult personality based on the Five-Factor Model (FFM) of personality. 
The FFM is taxonomy of personality traits in terms of five broad dimensions (the "BIG FIVE"): Neuroticism, Extraversion, Openness to Experience, Agreeableness, and Conscientiousness. 
It offers a conceptually useful framework for understanding the structure and systems of Axis II personality disorders.

In only 35-45 minutes, the NEO PI-R provides a systematic assessment of emotional, interpersonal, experiential, attitudinal, and motivational styles. 
The NEO PI-R is validated against other personality inventories, as well as projective assessments.

# Domains & facets
Each of the five domains of the NEO PI-R is represented by six specific scales that measure the facets of the domain.

|N: Neuroticism            |E: Extraversion        |O: Openness    |A: Agreeableness        |C: Conscientiousness     |
|----                      |---                    |---            |---                     |---                      |
|N1: Anxiety               |E1: Warmth             |O1: Fantasy    |A1: Trust               |C1: Competence           |
|N2: Angry, Hostility      |E2: Gregariousness     |O2: Aesthetics |A2: Straightforwardness |C2: Order                |
|N3: Depression            |E3: Assertiveness      |O3: Feelings   |A3: Altruism            |C3: Dutifulness          |
|N4: Self-conscientiousness|E4: Activity           |O4: Action     |A4: Modesty             |C4: Achievement striving |
|N5: Impulsiveness         |E5: Excitement-seeking |O5: Ideas      |A5: Modesty             |C5: Self-discipline      |
|N6: Vulnerability         |E6: Positive emotions  |O6: Values     |A6: Tender-mindedness   |C6: Deliberation         |


The NEO PI-R is a concise measure of the five major domains of personality, as well as the six traits or facets that define each domain. Taken together, the five domain scales and 30 facet scales of the NEO PI-R facilitate a comprehensive and detailed assessment of normal adult personality. The NEO PI-R has useful applications in counselling, clinical psychology, psychiatry, behavioural medicine and health psychology, vocational counselling and industrial/organizational psychology, and educational and personality research.

- **Neuroticism (N)** - refers to the chronic level of emotional adjustment and instability. High N identifies individuals who are prone to psychological distress.    
- **Extraversion (E)** - refers to the quantity and intensity of preferred interpersonal interactions, activity level, need for stimulation, and capacity for joy. High E identifies individuals who tend to be sociable, active, talkative, person oriented, optimistic, fun loving, and affectionate.  
- **Openness to Experience (O)** - refers to the active seeking and appreciation of experiences for their own sake. High O identifies individuals who are curious, imaginative, and willing to entertain novel ideas and unconventional values.  
- **Agreeableness (A)** - refers to the kinds of interactions an individual prefers along a continuum from compassion to antagonism. High A identifies individuals who tend to be soft-hearted, good natured, trusting, helpful, forgiving, and altruistic.  
- **Conscientiousness (C)** - assesses the degree of organization, persistence, control, motivation in goal-directed behaviour. High C identifies individuals who tend to be organized, reliable, hard-working, self-directed, punctual, scrupulous, ambitious, and persevering.  


# Administration & Scoring
The NEO PI-R is self-administered and is available in two parallel versions. 
Each version contains 240 items and 3 validity items, and requires a 6th grade reading level.

Form S, designed for self-reports, is appropriate for use with adult men and women, including individuals of college age.
Form R, designed for observer reports, is written in the third person for peer, spouse, or expert ratings. Use as an alternative measure or as a supplement to self-reports from adult clients.
Each item is rated on a 5-point Likert scale.
Internal consistency coefficients for both Forms R and S range from .86-.95 for domain scales and from .56-.90 for facet scales.
The NEO PI-R is validated against other personality inventories as well as projective techniques.

**At LCBC we have used the S-form**.

# Reliability
_from [wikipedia](https://en.wikipedia.org/wiki/Revised_NEO_Personality_Inventory)_
The internal consistency of the NEO scales was assessed on 1,539 individuals (McCrae & Costa,2010). 
The internal consistency of the NEO PI-R was high, at: N = .92, E = .89, O = .87, A = .86, C = .90. The internal consistency of the facet scales ranged from .56 to .81. 
The internal consistency of the NEO PI-3 was consistent with that of the NEO PI-R, with α ranging from .89 to .93 for the five domains. 
Internal consistency coefficient from the facets, with each facet scale comprising fewer items than each of the Big Five scales, were necessarily smaller, ranging from .54 to .83 (McCrae & Costa,2010).

The NEO has been translated into many languages. The internal consistency coefficients of the domain scores of a translation of the NEO that has been used in the Philippines are satisfactory. The alphas for the domain scores range from .78 to .90 (Church & Katigbak, 2002), with facet alphas having a median of .61 (Katigbak et al. 2002). 
Observer-ratings NEO PI-R data from 49 different cultures was used as criterion in a recent study which tested whether individuals' perceptions of the "national character" of a culture accurately reflected the personality of the members of that culture (it did not) (Terracciano et al. 2005).

The test-retest reliability of the NEO PI-R has also been found to be satisfactory. 
The test-retest reliability of an early version of the NEO after 3 months was: N = .87, E = .91, O = .86 (McCrae & Costa, 1983). 
The test-retest reliability for over 6 years, as reported in the NEO PI-R manual, was the following: N = .83, E = .82, O = .83, A = .63, C = .79. Costa and McCrae pointed out that these findings not only demonstrate good reliability of the domain scores, but also their stability (among individuals over the age of 30). 
Scores measured six years apart varied only marginally more than scores measured a few months apart (Costa & McCrae, 1992).

The psychometric properties of NEO PI-R scales have been found to generalize across ages, cultures, and methods of measurement(McCrae et al. 2011).


# References
McCrae, R. R., & Costa, P. T., Jr., (2010). NEO Inventories: Professional manual. _Lutz, FL: Psychological Assessment Resources, Inc._

Church, A. T.; Katigbak, M. S. (2002). "Indigenization of psychology in the Philippines". _International Journal of Psychology_. **37** (3): 129–148. [doi:10.1080/00207590143000315](https://doi.org/10.1080%2F00207590143000315).

Katigbak, M. S.; Church, A. T.; Guanzon-Lapeña, M. A.; Carlota, A. J.; Del, G. H. (2002). "Are indigenous personality dimensions culture specific? Philippine inventories and the five-factor model". _Journal of Personality and Social Psychology_. **82** (1): 89–101. [doi:10.1037/0022-3514.82.1.89](https://doi.org/10.1037%2F0022-3514.82.1.89). PMID [11811638](https://pubmed.ncbi.nlm.nih.gov/11811638).

Terracciano, A.; Abdel-Khalek, A. M.; Adám, N.; Adamovová, L.; Ahn, CK; Ahn, HN; Alansari, BM; Alcalay, L; Allik, J; Angleitner, A; Avia, MD; Ayearst, LE; Barbaranelli, C; Beer, A; Borg-Cunen, MA; Bratko, D; Brunner-Sciarra, M; Budzinski, L; Camart, N; Dahourou, D; De Fruyt, F; De Lima, MP; Del Pilar, GE; Diener, E; Falzon, R; Fernando, K; Ficková, E; Fischer, R; Flores-Mendoza, C; Ghayur, MA (2005). "National Character Does Not Reflect Mean Personality Trait Levels in 49 Cultures". _Science_. **310** (5745): 96–100. [Bibcode:2005Sci...310...96T](https://ui.adsabs.harvard.edu/abs/2005Sci...310...96T). [doi:10.1126/science.1117199](https://doi.org/10.1126%2Fscience.1117199). PMC [2775052](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC2775052). PMID [16210536](https://pubmed.ncbi.nlm.nih.gov/16210536).

McCrae R. R.; Kurtz J. E.; Yamagata S.; Terracciano A. (2011). "Internal consistency, retest reliability, and their implications for personality scale validity". _Pers Soc Psychol Rev_. **15** (1): 28–50. [doi:10.1177/1088868310366253](https://doi.org/10.1177%2F1088868310366253). PMC [2927808](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC2927808). PMID [20435807](https://pubmed.ncbi.nlm.nih.gov/20435807).

McCrae, R. R.; Costa, P. T. (1983). "Joint factors in self-reports and ratings: Neuroticism, extraversion and openness to experience". _Personality and Individual Differences_. **4** (3): 245–255. [doi:10.1016/0191-8869(83)90146-0](https://doi.org/10.1016%2F0191-8869%2883%2990146-0).

Costa, P. T., Jr., & McCrae, R. R. (1992). NEO PI-R professional manual. _Odessa, FL: Psychological Assessment Resources, Inc._
